sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t claragaset/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true claragaset/docker-react npm run test